require:
  - rubocop-rails

Layout/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "config/**/*.rb"
    - "db/migrate/*.rb"
    - "test/**/*sample_data*.rb"
    - "e2e/**/*test.rb"

Style/FormatStringToken:
  Exclude:
    - "config/routes.rb"

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Max: 1000

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
    - "config/**/*.rb"

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Metrics/ParameterLists:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "config/**/*.rb"
    - "db/migrate/*.rb"
    - "db/schema.rb"
    - "spec/factories/**/*.rb"
    - "app/admin/*.rb"
    - "app/admin/**/*.rb"
    - "lib/tasks/**/*.rake"

Layout/SpaceAroundEqualsInParameterDefault:
  Exclude:
    - "config/**/*.rb"
    - "db/migrate/*.rb"

  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/FormatString:
  EnforcedStyle: percent

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: "inject"


Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Lint/SafeNavigationChain:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Lint/SuppressedException:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BlockDelimiters:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: true

# Check with yard instead.
Style/Documentation:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "config/initializers/datadog-tracer.rb"

Lint/Debugger:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 11
  Severity: warning

Metrics/PerceivedComplexity:
  Max: 11
  Severity: warning

Metrics/AbcSize:
  Max: 35
  Severity: warning
  Exclude:
    - "config/**/*.rb"
    - "db/migrate/*.rb"


Style/RegexpLiteral:
  EnforcedStyle: "slashes"

Layout/IndentationConsistency:
  Severity: error

Rails:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false
  
Rails/Blank:
  Exclude:
    - "bin/*"

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  Exclude:
    - "tmp/**/*"
    - ".bundle/**/*"
    - "vendor/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "lib/schemas/**/*"
    - "config/deploy.rb"
    - "Dockerfile.ci"
    - "Dockerfile.rails"
    - "Dockerfile.ruby"
    - "bin/*"